"use client";

import { BarChart3, BellRing, Facebook, Eye, Clapperboard, Link2, Package, Plug, Settings, Users, WalletCards, PanelLeftClose } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Brand } from "./brand";

const navigation = [{ href: "/dashboard", label: "Dashboard", icon: BarChart3 }, { href: "/paginas-internas", label: "Páginas internas", icon: Facebook }, { href: "/paginas-monitoradas", label: "Páginas monitoradas", icon: Eye }, { href: "/videos-validados", label: "Vídeos validados", icon: Clapperboard }, { href: "/inspiracoes", label: "Inspirações", icon: BellRing }, { href: "/utms", label: "UTMs", icon: Link2 }, { href: "/produtos", label: "Produtos", icon: Package }, { href: "/financeiro", label: "Financeiro", icon: WalletCards }, { href: "/integracoes", label: "Integrações", icon: Plug }];
const admin = [{ href: "/usuarios", label: "Usuários", icon: Users }, { href: "/configuracoes", label: "Configurações", icon: Settings }];

export function AppSidebar() { const pathname = usePathname(); const item = (entry: typeof navigation[number]) => { const Icon = entry.icon; const active = pathname === entry.href; return <Link key={entry.href} href={entry.href} className={`nav-link ${active ? "nav-link-active" : ""}`}><Icon size={16} strokeWidth={active ? 2.25 : 1.8} />{entry.label}</Link>; }; return <aside className="sticky top-0 hidden h-screen w-[244px] shrink-0 flex-col border-r border-[var(--line)] bg-[oklch(0.12_0.008_20)] p-4 lg:flex"><div className="flex h-12 items-center justify-between border-b border-[var(--line)] pb-4"><Brand /><PanelLeftClose size={17} className="text-[var(--muted)]" /></div><nav className="mt-5 space-y-1">{navigation.map(item)}</nav><div className="mt-6 border-t border-[var(--line)] pt-5"><p className="mb-2 px-2 text-[10px] font-bold tracking-[.12em] text-[var(--muted)]">ADMINISTRAÇÃO</p><div className="space-y-1">{admin.map(item)}</div></div><div className="mt-auto rounded-lg border border-[var(--line)] bg-[var(--surface)] p-3"><p className="m-0 text-xs font-semibold text-white">Integrações</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Configure fontes de dados quando tiver as credenciais.</p><Link href="/integracoes" className="mt-2 inline-block text-xs font-semibold text-[#f3b2a2] hover:text-white">Ver integrações →</Link></div></aside>; }
