"use client";

import { createClient } from "@/lib/supabase/client";
import type { Field, Resource } from "@/lib/resource-config";
import { X } from "lucide-react";
import { useState } from "react";

type Row = Record<string, unknown>;
function normalize(field: Field, value: string) { if (!value.trim()) return null; if (field.type === "number") return Number(value.replace(",", ".")); if (field.key === "tags") return value.split(",").map(t => t.trim()).filter(Boolean); if (field.key === "config") { try { return JSON.parse(value); } catch { return { note: value }; } } return value; }
export function ResourceForm({ resource, row, onClose, onSaved }: { resource: Resource; row?: Row | null; onClose: () => void; onSaved: () => void }) { const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(resource.fields.map(f => [f.key, Array.isArray(row?.[f.key]) ? (row![f.key] as string[]).join(", ") : f.key === "config" && row?.[f.key] ? JSON.stringify(row[f.key], null, 2) : String(row?.[f.key] ?? "")] ))); async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const supabase = createClient(); const payload = Object.fromEntries(resource.fields.map(field => [field.key, normalize(field, values[field.key] || "")]).filter(([, v]) => v !== null)); const result = row?.id ? await supabase.from(resource.table).update(payload).eq("id", String(row.id)) : await supabase.from(resource.table).insert(payload); if (result.error) throw result.error; onSaved(); onClose(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível salvar o registro."); } finally { setBusy(false); } } return <div className="fixed inset-0 z-40 flex items-end justify-center bg-black/65 p-0 sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-label={`Cadastro de ${resource.singular}`}><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-xl border border-[var(--line)] bg-[var(--surface)] shadow-2xl sm:rounded-xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[var(--line)] bg-[var(--surface)] px-5 py-4"><div><h2 className="m-0 text-base font-semibold text-white">{row ? `Editar ${resource.singular}` : `Nova ${resource.singular}`}</h2><p className="mb-0 mt-1 text-xs text-[var(--muted)]">Os campos podem ser complementados depois.</p></div><button type="button" aria-label="Fechar" onClick={onClose} className="btn !p-2"><X size={17}/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2">{resource.fields.map(field => <FieldInput key={field.key} field={field} value={values[field.key] || ""} onChange={(value) => setValues(v => ({ ...v, [field.key]: value }))}/>)}</div>{error && <p className="mx-5 rounded-lg bg-red-500/10 px-3 py-2 text-xs text-red-200">{error}</p>}<div className="sticky bottom-0 flex justify-end gap-2 border-t border-[var(--line)] bg-[var(--surface)] px-5 py-4"><button type="button" onClick={onClose} className="btn">Cancelar</button><button disabled={busy} className="btn btn-primary disabled:cursor-not-allowed disabled:opacity-60">{busy ? "Salvando…" : "Salvar registro"}</button></div></form></div>; }
function FieldInput({ field, value, onChange }: { field: Field; value: string; onChange: (value: string) => void }) { const id = `field-${field.key}`; const base = <><label htmlFor={id} className="mb-1.5 block text-xs font-semibold text-[#ddd5d3]">{field.label}{field.required && <span className="text-[#f3a392]"> *</span>}</label>{field.hint && <p className="-mt-0.5 mb-1.5 text-[11px] text-[var(--muted)]">{field.hint}</p>}</>; if (field.type === "textarea") return <div className="sm:col-span-2">{base}<textarea id={id} value={value} onChange={e => onChange(e.target.value)} className="input min-h-24 resize-y" required={field.required}/></div>; if (field.type === "select") return <div>{base}<select id={id} value={value} onChange={e => onChange(e.target.value)} className="input" required={field.required}><option value="">Selecionar…</option>{field.options?.map(option => <option key={option} value={option}>{option.replace(/_/g, " ")}</option>)}</select></div>; return <div>{base}<input id={id} type={field.type || "text"} value={value} onChange={e => onChange(e.target.value)} className="input" required={field.required}/></div>; }
