import type { LucideIcon } from "lucide-react";
import { Box, Clapperboard, Eye, Facebook, Link2, Package, Plug, Users } from "lucide-react";

export type Field = { key: string; label: string; type?: "text" | "url" | "number" | "textarea" | "select" | "date"; options?: string[]; required?: boolean; hint?: string };
export type Resource = { table: string; singular: string; plural: string; description: string; icon: LucideIcon; fields: Field[]; list: string[] };

const common = { required: true };
export const resources: Record<string, Resource> = {
  "paginas-internas": { table: "facebook_pages", singular: "página", plural: "Páginas internas", description: "Ativos próprios do Facebook vinculados à operação.", icon: Facebook, list: ["name", "niche", "country_language", "status", "created_at"], fields: [{ key: "name", label: "Nome da página", ...common }, { key: "url", label: "URL da página", type: "url", ...common }, { key: "niche", label: "Nicho" }, { key: "country_language", label: "País / idioma", hint: "Ex.: Brasil / pt-BR" }, { key: "main_product_id", label: "ID do produto principal" }, { key: "status", label: "Status", type: "select", options: ["ativa", "pausada", "bloqueada", "em_teste"] }, { key: "notes", label: "Observações", type: "textarea" }, { key: "tags", label: "Tags", hint: "Separe por vírgulas" }] },
  "paginas-monitoradas": { table: "monitored_pages", singular: "página monitorada", plural: "Páginas monitoradas", description: "Referências externas salvas manualmente, sem coleta não autorizada.", icon: Eye, list: ["name", "niche", "country_language", "status", "created_at"], fields: [{ key: "name", label: "Nome", ...common }, { key: "url", label: "URL", type: "url", ...common }, { key: "niche", label: "Nicho" }, { key: "country_language", label: "País / idioma" }, { key: "monitoring_reason", label: "Motivo do monitoramento" }, { key: "status", label: "Status", type: "select", options: ["acompanhando", "arquivada", "prioritaria"] }, { key: "notes", label: "Observações", type: "textarea" }, { key: "tags", label: "Tags" }] },
  "videos-validados": { table: "videos", singular: "vídeo", plural: "Vídeos validados", description: "Biblioteca interna de criativos que passaram pela validação da operação.", icon: Clapperboard, list: ["title", "country_language", "platform", "creative_type", "status", "published_at"], fields: [{ key: "title", label: "Título", ...common }, { key: "video_url", label: "URL externa do vídeo", type: "url" }, { key: "thumbnail_url", label: "URL da thumbnail", type: "url" }, { key: "country_language", label: "País / idioma" }, { key: "platform", label: "Plataforma", type: "select", options: ["Facebook", "Instagram", "TikTok", "YouTube", "Outra"] }, { key: "creative_type", label: "Tipo de criativo", type: "select", options: ["UGC", "receita", "prova", "curiosidade", "dor", "depoimento", "antes_depois", "outro"] }, { key: "hook", label: "Hook", type: "textarea" }, { key: "copy", label: "Copy", type: "textarea" }, { key: "cta", label: "CTA" }, { key: "status", label: "Status", type: "select", options: ["em_teste", "validado", "escalado", "pausado"] }, { key: "published_at", label: "Data de publicação", type: "date" }, { key: "notes", label: "Observações", type: "textarea" }, { key: "tags", label: "Tags" }] },
  inspiracoes: { table: "inspirations", singular: "inspiração", plural: "Inspirações", description: "Vídeos e posts externos preservados como referência, isolados dos criativos próprios.", icon: Eye, list: ["title", "niche", "country", "discovered_at", "created_at"], fields: [{ key: "source_url", label: "Link do vídeo/post", type: "url", ...common }, { key: "title", label: "Título ou nota interna" }, { key: "thumbnail_url", label: "URL da thumbnail", type: "url" }, { key: "niche", label: "Nicho" }, { key: "country", label: "País" }, { key: "reason_saved", label: "Por que foi salvo", type: "textarea" }, { key: "discovered_at", label: "Data da descoberta", type: "date" }, { key: "notes", label: "Observações", type: "textarea" }, { key: "tags", label: "Tags" }] },
  produtos: { table: "products", singular: "produto", plural: "Produtos", description: "Catálogo que conecta páginas, vídeos, UTMs e vendas.", icon: Package, list: ["name", "price", "currency", "offer_country", "status", "created_at"], fields: [{ key: "name", label: "Nome", ...common }, { key: "description", label: "Descrição", type: "textarea" }, { key: "checkout_url", label: "Link do checkout", type: "url" }, { key: "price", label: "Preço", type: "number" }, { key: "currency", label: "Moeda", type: "select", options: ["BRL", "USD", "EUR"] }, { key: "offer_country", label: "País de oferta" }, { key: "status", label: "Status", type: "select", options: ["ativo", "pausado", "arquivado"] }, { key: "notes", label: "Observações", type: "textarea" }] },
  utms: { table: "utm_links", singular: "UTM", plural: "UTMs", description: "Links rastreáveis para atribuição de páginas, criativos e produtos.", icon: Link2, list: ["internal_name", "final_url", "utm_medium", "utm_campaign", "status", "created_at"], fields: [{ key: "internal_name", label: "Nome interno", ...common }, { key: "base_url", label: "URL base", type: "url", ...common }, { key: "utm_source", label: "utm_source", hint: "Sugestão: facebook" }, { key: "utm_medium", label: "utm_medium", hint: "organic, paid ou influencer" }, { key: "utm_campaign", label: "utm_campaign" }, { key: "utm_content", label: "utm_content" }, { key: "utm_term", label: "utm_term" }, { key: "status", label: "Status", type: "select", options: ["ativa", "pausada", "arquivada"] }, { key: "notes", label: "Observações", type: "textarea" }] },
  integracoes: { table: "integrations", singular: "integração", plural: "Integrações", description: "Conecte serviços somente depois de informar credenciais e documentação autorizadas.", icon: Plug, list: ["name", "provider", "status", "last_synced_at", "updated_at"], fields: [{ key: "name", label: "Nome", ...common }, { key: "provider", label: "Provedor", ...common }, { key: "status", label: "Status", type: "select", options: ["nao_configurada", "conectada", "erro", "sincronizando"] }, { key: "config", label: "Configuração não sensível (JSON)", type: "textarea" }] },
  usuarios: { table: "profiles", singular: "usuário", plural: "Usuários", description: "Gestão de perfis. Convites e senhas são controlados pelo Supabase Auth por um administrador.", icon: Users, list: ["full_name", "email", "role", "created_at"], fields: [{ key: "full_name", label: "Nome completo", ...common }, { key: "email", label: "E-mail", type: "text", ...common }, { key: "role", label: "Perfil", type: "select", options: ["admin", "gestor", "operador"] }] }
};

export function labelFor(key: string) { return key.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
